FROM amd64/mongo:8.0.0

ENV MONGO_INITDB_ROOT_USERNAME=${DB_USER}
ENV MONGO_INITDB_ROOT_PASSWORD=${DB_PASSWORD}
ENV MONGO_INITDB_DATABASE=${DB_NAME}

COPY init.js /docker-entrypoint-initdb.d/

EXPOSE 27017
